CC=iverilog
EXECNAME=coretb

all:
	$(CC) -o $(EXECNAME) coretb_v5r0.v ../core/core_v5r0.v ../core/machine_v1r0.v testmem_v1r0.v ../core/sysx_v1r0.v ../core/sdram_v1r0.v ../io/controller_v1r0.v ../io/gpio_v1r0.v ../core/rom_v1r0.v ../io/uart_v1r0.v ../io/spi_v1r0.v ../io/video_v1r0.v

